### ISSUE TITLE
enable cleanly deleting cloud resources by removing application components and ingress

### ISSUE THREAD

**Issue by tdaly61** [openMF/mojafos#16]
we need to destroy things very often in the reverse order in which they are installed. So for k3s or microk8s  locally you can simply do a cleanup of the k8s server and  then everything goes away BUT (and this is important) if you try to remove (say) an AWS EKS cluster that still has running apps and still has (especially) an active nginx and load balancer => it leaves an awful awful mess that takes a long time to clean up and leaves resources around that "cost money" !!!!  So can  I refer you top vNext beta  mini-loop directory and the eks-setup tools in the vNext Beta that back out the apps and then back out the nginx and LB etc and then (and only then) do they remove infrastructure.

**Comment by elijah0kello** [comment]
The implementation of this is complete. Will be updated in the next PR
